### ISSUE TITLE
when nuget package in "Validating" status

### ISSUE THREAD

**Issue by mindfocus** [brandedoutcast/publish-nuget#32]
upload package error

```

##[error]😭 error: Response status code does not indicate success: 409 (A package with ID 'sabre.net' and version '1.0.4' already exists and cannot be modified.).
/home/runner/work/_actions/rohith/publish-nuget/v2/index.js:23
        throw new Error(msg)
        ^

Error: error: Response status code does not indicate success: 409 (A package with ID 'sabre.net' and version '1.0.4' already exists and cannot be modified.).
    at Action._printErrorAndExit (/home/runner/work/_actions/rohith/publish-nuget/v2/index.js:23:15)
    at Action._pushPackage (/home/runner/work/_actions/rohith/publish-nuget/v2/index.js:73:18)
    at IncomingMessage.<anonymous> (/home/runner/work/_actions/rohith/publish-nuget/v2/index.js:109:30)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

```

**Comment by mindfocus** [comment]
I think it's just a tip more than an error, right?

**Comment by LegendaryB** [comment]
Experienced the same. Looks like it is really just an warning. But I would prefer when it would be logged as warning under actions. So that I can also see that the packages which are published afterwards are pushed. What do you think @brandedoutcast

**Comment by brandedoutcast** [comment]
@mindfocus @LegendaryB I'm not quite sure in what scenario you get this but the action should've just skipped creating a package altogether when there's a package with same name & version. Also the `--skip-duplicate` flag should've handled it even if there was an existing package
